### ISSUE TITLE
Chrome driver issue

### ISSUE THREAD

**Issue by Ravi-099** [dvalbuena1/visa_rescheduler_aws#13]
It looks like the Chrome driver URL is not fetching the driver. I was able to get around this issue by downloading the driver manually and specifying the path in the script def get_driver():

Error message
  File "E:\Program Files (x86)\Python 3.10\lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip

**Comment by dvalbuena1** [comment]
Thanks for letting me know.
The problem was the `webdriver-manager` library, this bug has been fixed in the latest version of the library.
I just did a commit 5d19671565c310d2df60e413b5917880b1a695a7 with the newer version. Or you can update the library by executing `pip install --upgrade webdriver-manager`

Let me know if this works for you
