### ISSUE TITLE
Multi Account Possible?

### ISSUE THREAD

**Issue by injusticiaenarm** [dvalbuena1/visa_rescheduler_aws#18]
Would it be possible to have this run a few accounts (pull USER, PASSOWRD and DESIRED OFFICE from a small database) and mark them as done so it doesnt run the code for that account once a certain timeframe has been reached (i.e. any date before an specific date or any date x days from today).

The code would either run on separate instances for each account or make one try with the first account, then skip to the next and so on on a loop. 
Is this possible?

Also, quick question... Does this work for both instances where the person needs both a consular and ASC (biometrics) appointment and when its only an renewal and only needs one of them?

@dvalbuena1 

Thanks.

**Comment by injusticiaenarm** [comment]
Anything? :( I dont expect you to do it. I just want to know if it can be done and what would the best approach be. Then I can look it up and do so.

I have no prior python experience, but  know some Javascript, PHP,HTML and CSS so I guess I could find a way to do so. Just need a little guidance.

**Comment by dvalbuena1** [comment]
There is no single answer to what you mention, as there may be multiple ways of doing it.

Since the code right now doesnt support that, you could try and refactor the code so when you read the config.ini file you iterate throught an array of users, or some thing like that. That means and array of USERNAME, PASSWORD, SCHEDULE_ID and NEED_ASC. An easier way could be just use a JSON file instead of a .ini File and there you have an array of objects where each object has the necessary information.

Another option would be not to edit the code but to go further to AWS and change the infrastructure where maybe the information of each user is stored and the only thing you need to do is to call the lambda function with this information. This approach requires more AWS knowledge.

It's up to you to check which option is best for you.
